# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Sum a vector (C/C++ internal implementation)
#'
#' Return the sum of all the elements in a vector.
#' @param x a numeric vector
#' @return numeric(1)
#' @author Timothee Flutre
#' @export
sumVec_cpp_int <- function(x) {
    .Call('timTestRcppGSL_sumVec_cpp_int', PACKAGE = 'timTestRcppGSL', x)
}

#' Sum a vector (C/C++ external implementation)
#'
#' Return the sum of all the elements in a vector.
#' @param x a numeric vector
#' @return numeric(1)
#' @author Timothee Flutre
#' @export
sumVec_cpp_ext <- function(x) {
    .Call('timTestRcppGSL_sumVec_cpp_ext', PACKAGE = 'timTestRcppGSL', x)
}

